### ISSUE TITLE
System Tests:  Fuzz Testing

### ISSUE THREAD

**Issue by nkuba** [keep-network/keep-ecdsa#389]
Set-up a fuzz-testing instance with go-fuzz especially for parts that are parsing/handling untrusted input, in an effort to find yet uncaught potentially triggerable panic conditions

**Comment by lukasz-zimnoch** [comment]
**Fuzz tests for network layer**

Performed fuzz testing of the network layer on two levels. Those tests include `keep-ecdsa` and `keep-core` as well because the whole network layer is implemented here.

**Level 1**

On this level, we added multiple fuzzing tests that cover the unmarshaling logic of all network layer types. From a bit higher perspective, we also added some scenarios which perform fuzzing on broadcast and unicast channels. During those tests, several unexpected panic conditions were detected and fixed. Two PR covers this level:
- [keep-ecdsa: Fuzz testing - network layer unit tests with google/gofuzz](https://github.com/keep-network/keep-ecdsa/pull/390)
- [keep-core: Fuzz testing - network layer unit tests with google/gofuzz](https://github.com/keep-network/keep-core/pull/1599)

**Level 2**

Here we performed some end-to-end tests on real `keep-ecdsa` and `keep-core` networks using some malicious clients that sent random messages during protocol execution. No unexpected panics detected at this stage. Here is a PR which introduces a document with detailed description:
- [E2E Fuzz testing with a malicious client](https://github.com/keep-network/keep-test/pull/2)
