### ISSUE TITLE
Bonded sortition pool re-joining after running out of Eth

### ISSUE THREAD

**Issue by knarz** [keep-network/keep-ecdsa#500]
Over the past couple of days I've observed that once a node gets kicked from the bonded sortition pool, because it ran out of Eth for bonding, it has a hard time rejoining. Calls to `RegisterAsMemberCandidate` in `pkg/chain/ethereum/ethereum.go` are queued, I think, but it seems like they're never executed even if more Eth are added for bonding.

1. Run out of Eth for bonding
2. Operator gets kicked from bonded sortition pool
3. Node logs `Operator not eligible` errors
4. Add more Eth for bonding
5. Node continues to log errors

A restart of the node remedies this, which is not perfect.

I was also able to fix it by just calling `registerMemberCandidate` on chain via an external script. This returns the node to normal operation but also requires outside intervention

**Comment by mhluongo** [comment]
Thank you for doing the legwork here @knarz! We'll check it out

**Comment by pdyraga** [comment]
I tried to replicate this problem with no luck, I see the client behaves as expected.

[Looking at the code in `pkg/client/registration.go`](https://github.com/keep-network/keep-ecdsa/blob/4cf63d2e018bc0da8e49c1d2302e0c3fbdc82fdf/pkg/client/registration.go), `checkStatusAndRegisterForApplication` registers the client to the application and triggers status monitoring; in the case when `monitorSignerPoolStatus` exits with an error - and it happens when the client is kicked out of the sortition pool - it tries to register the operator again and monitors the progress every block in `waitUntilRegistered`. From the code perspective, it all looks as expected.

I created two simple scripts - one withdrawing unbonded value from `KeepBonding` and another depositing 50 ETH to `KeepBonding`. I executed withdraw-deposit cycle multiple times and the client handled it all correctly, automatically registering the staker back to the pool. I have also executed the smoke test opening a keep and requesting a signature from that keep and I see that the client who registered back to the sortition pool was properly selected to the signer set and cooperated with other clients.

```
14:38:58.060 DEBUG keep-ecdsa: operator status check for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] triggered at block [5266] registration.go:241
14:38:58.061 DEBUG keep-ecdsa: operator status is up to date for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:258
14:39:10.667 DEBUG keep-ecdsa: operator status check for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] triggered at block [5271] registration.go:241
14:39:10.668 DEBUG keep-ecdsa: operator status is up to date for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:258
14:39:50.826 DEBUG keep-ecdsa: operator status check for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] triggered at block [5276] registration.go:241
14:39:50.827  INFO keep-ecdsa: updating operator status for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:263
14:39:50.827 DEBUG keep-contr: submitting transaction updateOperatorStatus params:  [101 234 85 193 241 4 145 3 132 37 114 93 192 13 255 234 178 161 226 138] [79 124 119 26 177 115 190 194 187 233 128 73 113 17 134 99 131 162 17 114] BondedECDSAKeepFactory.go:529
14:39:50.828  INFO keep-ethut: local nonce [0] is lower than pending [64]; updating local nonce nonce.go:104
14:39:50.861  INFO keep-contr: submitted transaction updateOperatorStatus with id: [0x04015c58ec8bf65ccbfc211ed52095acb2a552513dce587f03915cff229b2eef] and nonce [64] BondedECDSAKeepFactory.go:576
14:39:50.861 DEBUG keep-chain: submitted UpdateOperatorStatus transaction with hash: [04015c58ec8bf65ccbfc211ed52095acb2a552513dce587f03915cff229b2eef] ethereum.go:378
14:39:50.861  INFO keep-ecdsa: waiting for block [5288] to confirm chain state client.go:815
14:40:01.867  INFO keep-ethut: transaction [04015c…9b2eef] mined with status [1] at block [5277] mine_waiter.go:108
(...)
14:41:08.601 ERROR keep-ecdsa: failed on signer pool status monitoring: [operator is no longer registered for application [0x4f7C771Ab173bEc2BbE980497111866383a21172]] registration.go:56
14:41:09.720 WARNI keep-ecdsa: operator is not eligible for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:138
14:41:14.833 WARNI keep-ecdsa: operator is not eligible for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:138
14:41:23.048 WARNI keep-ecdsa: operator is not eligible for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:138
14:41:34.916 WARNI keep-ecdsa: operator is not eligible for application [0x4f7C771Ab173bEc2BbE980497111866
14:43:54.107 WARNI keep-ecdsa: operator is not eligible for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:138
(...)
14:44:18.647  INFO keep-ecdsa: registering member candidate for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:148
14:44:18.647 DEBUG keep-contr: submitting transaction registerMemberCandidate params:  [79 124 119 26 177 115 190 194 187 233 128 73 113 17 134 99 131 162 17 114] BondedECDSAKeepFactory.go:798
14:44:18.685  INFO keep-contr: submitted transaction registerMemberCandidate with id: [0x96bfd9071cdb2c640dd76c446a53fe849594d4a6c9e57feb119b564cc5fdd9a1] and nonce [65] BondedECDSAKeepFactory.go:842
14:44:18.686 DEBUG keep-chain: submitted RegisterMemberCandidate transaction with hash: [96bfd9071cdb2c640dd76c446a53fe849594d4a6c9e57feb119b564cc5fdd9a1] ethereum.go:39
14:44:33.690  INFO keep-ethut: transaction [96bfd9…fdd9a1] not yet mined: [context deadline exceeded] mine_waiter.go:99
14:44:33.690  INFO keep-ethut: resubmitting previous transaction [96bfd9…fdd9a1] with a higher gas price [34560000000] mine_waiter.go:138
14:44:33.691  INFO keep-contr: submitted transaction registerMemberCandidate with id: [0x407f3cb410e3bea2f67537b8ba392f1c6198ec1689ebf3a1f9f1f705a29a579c] and nonce [65] BondedECDSAKeepFactory.go:868
14:44:37.202  INFO keep-ecdsa: operator is registered for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:195
14:44:37.202 DEBUG keep-ecdsa: starting monitoring operatator status for application [0x4f7C771Ab173bEc2BbE980497111866383a21172] registration.go:219
14:44:37.693  INFO keep-ethut: transaction [407f3c…9a579c] mined with status [1] at block [5310] mine_waiter.go:108


```

Script for withdrawing bond:
```
const KeepBonding = artifacts.require("KeepBonding.sol");

module.exports = async function() {
    try {
        const bonding = await KeepBonding.deployed()
        console.log(`Using KeepBonding[${bonding.address}]`)

        const operator = "0x65ea55c1f10491038425725dc00dffeab2a1e28a"
        let unbondedValue = await bonding.unbondedValue(operator)
        console.log(`Unbonded value: ${web3.utils.fromWei(unbondedValue)}`)

        await bonding.withdraw(unbondedValue, operator)
        console.log(`ETH withdrawn from KeepBonding`)

        unbondedValue = await bonding.unbondedValue(operator)
        console.log(`Unbonded value: ${web3.utils.fromWei(unbondedValue)}`)
    } catch (error) {
        console.log(error)
    }

    process.exit(0)
}
```

Script for depositing ETH:
```
const KeepBonding = artifacts.require("KeepBonding.sol");

module.exports = async function() {
    try {
        const bonding = await KeepBonding.deployed()
        console.log(`Using KeepBonding[${bonding.address}]`)

        const operator = "0x65ea55c1f10491038425725dc00dffeab2a1e28a"
        let unbondedValue = await bonding.unbondedValue(operator)
        console.log(`Unbonded value: ${web3.utils.fromWei(unbondedValue)}`)

        await bonding.deposit(operator, {value: web3.utils.toWei("50", "ether")})
        console.log(`ETH deposited to KeepBonding`)

        unbondedValue = await bonding.unbondedValue(operator)
        console.log(`Unbonded value: ${web3.utils.fromWei(unbondedValue)}`)
    } catch (error) {
        console.log(error)
    }

    process.exit(0)
}
```


What I think could happen to you:
- Client status in the sortition pool is checked every `100` blocks:
    https://github.com/keep-network/keep-ecdsa/blob/4cf63d2e018bc0da8e49c1d2302e0c3fbdc82fdf/pkg/client/registration.go#L12
   It means that the status - if outdated - is updated after ~30-40 minutes in a pessimistic case. To test this scenario locally, I tweaked this value to 5 blocks. Maybe you were just not waiting enough time after adding more ETH to `KeepBonding` contract?
- You said that you've seen calls to `RegisterAsMemberCandidate`. Are you sure the operator had enough ETH on the account to have those transactions mined? Do you have their hashes by any chance? I think what you describe as queued transactions are in fact resubmissions of the same transaction with increased gas price. Based on the configuration, the client monitors the status of a TX and may decide to resubmit it with a higher gas price if it hasn't been mined on time. Example:
  ```
  14:44:18.686 DEBUG keep-chain: submitted RegisterMemberCandidate transaction with hash: [96bfd9071cdb2c640dd76c446a53fe849594d4a6c9e57feb119b564cc5fdd9a1] ethereum.go:39
  14:44:33.690  INFO keep-ethut: transaction [96bfd9…fdd9a1] not yet mined: [context deadline exceeded] mine_waiter.go:99
  14:44:33.690  INFO keep-ethut: resubmitting previous transaction [96bfd9…fdd9a1] with a higher gas price [34560000000] mine_waiter.go:138
  14:44:33.691  INFO keep-contr: submitted transaction registerMemberCandidate with id: [0x407f3cb410e3bea2f67537b8ba392f1c6198ec1689ebf3a1f9f1f705a29a579c] and nonce [65] BondedECDSAKeepFactory.go:868
  ```

**Comment by jdnz** [comment]
I see the same issue. I added 12 Ropsten ETH yesterday and today it remains unbonded and in the logs I see "operator is not eligible for application" warnings, so I don't think it is a matter of not waiting long enough. Let me know of any tests I can run to help diagnose the issue.

**Comment by pdyraga** [comment]
@jdnz Can you please compress and attach full logs from your client? I'll also need information about your operator address and config file from your client.

**Comment by jdnz** [comment]
The log file is too big to attach here - 50M zipped. Anywhere I could drop them?
Operator address: 0x07b3FA33Ab19c1a98C1Fa2E0b2A7e363Ae9E8f19
Config file
```
# This is a TOML configuration file.

# Connection details of ethereum blockchain.
[ethereum]
  URL = "wss://ropsten.infura.io/ws/v3/5b4243c34ef04269a16eb274671cc8ae"
  URLRPC = "https://ropsten.infura.io/v3/5b4243c34ef04269a16eb274671cc8ae"

[ethereum.account]
  KeyFile = "/mnt/keep-ecdsa-client/config/keep-ecdsa-operator-account-keyfile"

# Addresses of contracts deployed on ethereum blockchain.
[ethereum.ContractAddresses]
  BondedECDSAKeepFactory = "0xe7BF8421fBE80c3Bf67082370D86C8D81D1D77F4"

# Addresses of applications approved by the operator.
[SanctionedApplications]
  Addresses = [
	"0x14dC06F762E7f4a756825c1A1dA569b3180153cB"
  ]

[Storage]
  DataDir = "/mnt/keep-ecdsa-client/persistence"

[LibP2P]
  Peers = ["/dns4/bootstrap-1.ecdsa.keep.test.boar.network/tcp/4001/ipfs/16Uiu2HAmPFXDaeGWtnzd8s39NsaQguoWtKi77834A6xwYqeicq6N", 
"/dns4/ecdsa-2.test.keep.network/tcp/3919/ipfs/16Uiu2HAmNNuCp45z5bgB8KiTHv1vHTNAVbBgxxtTFGAndageo9Dp",
"/dns4/ecdsa-3.test.keep.network/tcp/3919/ipfs/16Uiu2HAm8KJX32kr3eYUhDuzwTucSfAfspnjnXNf9veVhB12t6Vf",
]
  Port = 3919
  # Uncomment to override the node's default addresses announced in the network
  AnnouncedAddresses = []

[TSS]
# Timeout for TSS protocol pre-parameters generation. The value
# should be provided based on resources available on the machine running the client.
# This is an optional parameter, if not provided timeout for TSS protocol
# pre-parameters generation will be set to `2 minutes`.
  PreParamsGenerationTimeout = "2m30s"
```

**Comment by c29r3** [comment]
I'm seeing exactly the same problem  
`WARNI keep-ecdsa: operator is not eligible for application [0x14dC06F762E7f4a756825c1A1dA569b3180153cB] registration.go:138`

Client version: `keepnetwork/keep-ecdsa-client:v1.1.2-rc`

Config file:
```
[ethereum]
  URL = "wss://ropsten.infura.io/ws/v3/$INFURA_TOKEN"
  URLRPC = "https://ropsten.infura.io/v3/$INFURA_TOKEN"


[ethereum.account]
  Address = "0xc2C5b1F115b4c82fB0c1ce6208AcD7089e3B506D"
  KeyFile = "/mnt/keep-ecdsa/keystore/keep_wallet.json"

[ethereum.ContractAddresses]
  BondedECDSAKeepFactory = "0xe7BF8421fBE80c3Bf67082370D86C8D81D1D77F4"

[SanctionedApplications]
  Addresses = ["0x14dC06F762E7f4a756825c1A1dA569b3180153cB"]

[Storage]
  DataDir = "/mnt/keep-ecdsa/persistence"
  
[LibP2P]
  Peers = ["/dns4/testnet.keep-client.hashd.dev/tcp/3920/ipfs/16Uiu2HAmJsBiNVFNxsJ27NSQEByv39B1M7AKx5FrAc1htqYhHGhU","/ip4/3.23.88.229/tcp/3919/ipfs/16Uiu2HAmEZpkf1Td8rSBMmgPoa66si2kJLb83Rd2eztJ6f5oLvhp","/dns4/ecdsa-2.test.keep.network/tcp/3919/ipfs/16Uiu2HAmNNuCp45z5bgB8KiTHv1vHTNAVbBgxxtTFGAndageo9Dp",	
"/dns4/ecdsa-3.test.keep.network/tcp/3919/ipfs/16Uiu2HAm8KJX32kr3eYUhDuzwTucSfAfspnjnXNf9veVhB12t6Vf","/dns4/bootstrap-1.ecdsa.keep.test.boar.network/tcp/4001/ipfs/16Uiu2HAmPFXDaeGWtnzd8s39NsaQguoWtKi77834A6xwYqeicq6N"]
Port = 3919
 AnnouncedAddresses = ["/ip4/$EXTERNAL_IP/tcp/3919"]

[TSS]
  PreParamsGenerationTimeout = "2m30s"
```

**Comment by knarz** [comment]
The issue I reported here was about rejoining the bonded sortition pool by the node.

It appears that currently there's a problem joining the sortition pool which is not directly related to my initial report.

**Comment by pdyraga** [comment]
I think @knarz is right and what you experienced @jdnz is related to  #504. 

@knarz do you have by any chance logs from your client from the moment it tried to rejoin the pool? I am especially interested in transaction hashes and what happened when they were mined. I tried to replicate this issue again but it all works for me as expected.

**Comment by jdnz** [comment]
To clarify, this issue happened to me after my node ran out of bonded ETH and then I added more (not a new node like the other issue), so it seemed to fit with the original issue description. To update on my nodes status, up until around midnight UTC last night my node was still reporting "not eligible for application" warnings. It then tried to register for the application and is ever since reporting `operator is not yet registered for application [0x14dC06F762E7f4a756825c1A1dA569b3180153cB], waiting...`

**Comment by knarz** [comment]
@pdyraga sorry, I haven't had the time trying to reproduce this, yet, and also don't have the logs with transaction hash.

**Comment by pdyraga** [comment]
@JaviAnibarro, @c29r3 reported the same problem in #504 and @k0kk0k reported it worked fine without restarting the node. I think what happened is that a lot of nodes become ineligible and later they became eligible again more or less at the same time. I think it wasn't because adding more ETH to the bonding contract but because the minimum bond required by the sortition pool dropped down as a result of opening a smaller deposit.

What's happening is that if we have multiple sortition pool transactions queued, those mined at the end may no longer have valid gas limits as they were estimated based on a different state of the pool. 

I was able to reproduce this problem locally:
```
10:43:07.508  INFO keep-ecdsa: registering member candidate for application [0xB5136F3951547c8d430067f7fdF35c062C97563d] registration.go:85
10:43:07.508 DEBUG keep-contr: submitting transaction registerMemberCandidate params:  [181 19 111 57 81 84 124 141 67 0 103 247 253 243 92 6 44 151 86 61] BondedECDSAKeepFactory.go:623
10:43:07.508  INFO keep-ethut: local nonce [0] is lower than pending [7]; updating local nonce nonce.go:104
10:43:07.543  INFO keep-contr: submitted transaction registerMemberCandidate with id: [0xd2d0e6728f59695c3ddf4a1bf6b4f1dbd6f2935440fbc694c50528ec90bc7198] and nonce [7] BondedECDSAKeepFactory.go:667
10:43:18.038  INFO keep-ecdsa: operator is not yet registered for application [0xB5136F3951547c8d430067f7fdF35c062C97563d], waiting... registration.go:202
10:43:18.552  INFO keep-ethut: transaction [d2d0e6…bc7198] mined with status [0] at block [2721] mine_waiter.go:108
10:43:47.872  INFO keep-ecdsa: operator is not yet registered for application [0xB5136F3951547c8d430067f7fdF35c062C97563d], waiting... registration.go:202
10:43:52.860  INFO keep-ecdsa: operator is not yet registered for application [0xB5136F3951547c8d430067f7fdF35c062C97563d], waiting... registration.go:202
```

https://github.com/keep-network/keep-ecdsa/issues/506 I am currently working on such prevent from such a massive pool registration/unregistration events. At the same time, we can think about adding some gas limit safe margin for the sortition pool registration TX. It should also be clear in the logs (ERROR) that the registration transaction failed.

**Comment by jdnz** [comment]
Makes sense. I've restarted my node and it registered successfully.
