### ISSUE TITLE
Migrate to OpenZeppelin test environment

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-ecdsa#501]
We should update `keep-ecdsa` tests to OpenZeppelin test environment just like we did in `keep-core` (https://github.com/keep-network/keep-core/issues/1528).

While working on this issue, let's also explore if it is possible to move stubs somewhere into `solidity/tests` directory tree, as proposed in https://github.com/keep-network/keep-core/pull/1739. 

References:
- https://github.com/keep-network/keep-core/pull/1533
- https://github.com/keep-network/tbtc/pull/441

**Comment by eth-r** [comment]
It would be great if we could also migrate to a [parallel test runner, e.g. Jest](https://docs.openzeppelin.com/test-environment/0.1/choosing-a-test-runner) to make the tests even faster, as `keep-core` is getting rather slow again. Depending on the amount of work necessary for changing the runner (Jest seems quite similar to Mocha) it may be convenient to do it at the same time as the OZ migration.

**Comment by dimpar** [comment]
Agree, `Jest` is worth trying.  Per their doc, there are 2 main differences. I believe that migrating `keep-ecdsa` to OZ would align all keep-network apps using the same testing env. Since [PR](https://github.com/keep-network/keep-ecdsa/pull/502) for OZ is already opened, I would explore `Jest` in a separate PR.
